#
# Cookbook:: demo_yaml_chef_infra
# Recipe:: default
#
# Copyright:: 2021, The Authors, All Rights Reserved.

---
resources:
# Example Syntax
# Additional snippets are available using the Chef Infra Extension for Visual Studio Code
# - type: file
#   name: '/path/to/file'
#   content: 'content'
#   owner: 'root'
#   group: 'root'
#   mode: '0755'
#   action:
#     - create
