name 'demo_yaml_chef_infra'
maintainer 'Collin McNeese'
maintainer_email 'cmcneese@chef.io'
license 'Apache-2.0'
description 'Installs/Configures demo_yaml_chef_infra'
version '0.1.0'
chef_version '>= 16.0'
