# To learn more about Custom Resources, see https://docs.chef.io/custom_resources/

provides :demo_yaml_file_gen
resource_name :demo_yaml_file_gen

unified_mode true

property :path, String, name_property: true
property :content, String

action :create do
  file_content = [
    'This is a demo file generated by demo_yaml_chef_infra',
    node['fqdn'],
    node['platform'],
  ]

  file_content.append(new_resource.content) if new_resource.content

  file new_resource.path do
    content file_content.join("\n")
    action :create
  end
end
