# Chef InSpec test for recipe demo_yaml_chef_infra::default

# The Chef InSpec reference, with examples and extensive documentation, can be
# found at https://docs.chef.io/inspec/resources/

control 'demo_yaml_file' do
  impact 0.7
  title 'demo_yaml_file'
  desc 'File demo_yaml_file.txt should exist with generated content'

  describe.one do
    describe file('/var/chef/demo_yaml_chef_infra/demo_yaml_file.txt') do
      it { should exist }
      its('content') { should match /^This is a demo file generated by demo_yaml_chef_infra$/ }
    end
    describe file('C:/chef/demo_yaml_chef_infra/demo_yaml_file.txt') do
      it { should exist }
      its('content') { should match /^This is a demo file generated by demo_yaml_chef_infra$/ }
    end
  end
end
