name: cookbook

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  env:
    CHEF_LICENSE: accept-no-persist
  call-workflow-1:
    uses: collinmcneese/gh_workflows/.github/workflows/verify_cookbook.yml@main

