name: cookbook

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  verify_cookbook:
    uses: collinmcneese/gh_workflows/.github/workflows/verify_cookbook.yml@main
    env:
      CHEF_LICENSE: accept

